env: "local" # local, dev, prod
db:
  host: "0.0.0.0"
  port: 5432
  username: "username"
  password: "123"
  db_name: "db_name"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
admin_token: "admin_token"